displayName=Streamerbot Triggers
author=Darock
description=Send requests to Streamerbot using Dink notifiers.
tags=streaming, notifier, trigger, OBS, Streamerbot, Twitch, YouTube
plugins=streamerbot.StreamerbotPlugin